# Generated by Django 5.1 on 2024-09-01 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_level_user_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
        migrations.AddField(
            model_name='quiz',
            name='required_level',
            field=models.IntegerField(default=1),
        ),
    ]
