# Generated by Django 5.1 on 2024-09-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_learningmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='description',
        ),
    ]
